version: '3'
services:
    web:
        image: nginx:1.22.1
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - db
    php:
        #image: php:8.2-fpm-alpine
        #image: php:8.2-fpm
        build: ./
        volumes:
             - ./src:/var/www/html
        restart: always 
         
    # php:
    #     build: .docker
    #     restart: always
    #     volumes:
    #         - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    #         - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    #         - .:/var/www/html
    # composer:
    #     image: composer
    #     volumes:
    #         - .:/app
    #     command: install

    db:
        image: postgres:15.6
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
             - ./postgres/:/docker-entrypoint-initdb.d/    

# services:
#   nginx:
#     image: nginx:1.24
#     ports:
#       - 8077:80
#     volumes:
#       - ./src:/usr/share/nginx/html
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - php

  #healthcheck:
    #test: curl --fail http://localhost || exit 1
    #interval: 60s
    #retries: 5
    #start_period: 20s
    #timeout: 10s
