version: "3"
services:
  miroshnichenkoan-netology-db:    
    image: postgres:latest # Образ, который мы будем использовать    
    container_name: miroshnichenkoan-netology-db # Имя, которым будет называться наш контейнер    
    ports: # Порты, которые мы пробрасываем с нашего докер сервера внутрь контейнера      
      - 5432:5432    
    volumes: # Папка, которую мы пробросим с докер сервера внутрь контейнера      
      - ./pg_data:/var/lib/postgresql/data/pgdata    
    environment: # Переменные среды      
      POSTGRES_PASSWORD: miroshnichenkoan12!3!!  # Задаём пароль от пользователя postgres      
      POSTGRES_DB: miroshnichenkoan-db # БД которая сразу же будет создана        
      PGDATA: /var/lib/postgresql/data/pgdata # Путь внутри контейнера, где будет папка pgdata    
    networks:      
      miroshnichenkoan-my-netology-hw:        
        ipv4_address: 172.22.0.2    
    restart: always # Режим перезапуска контейнера. Контейнер всегда будет перезапускаться
  pgadmin:    
    image: dpage/pgadmin4    
    container_name: miroshnichenkoan-pgadmin    
    environment:      
      PGADMIN_DEFAULT_EMAIL: miroshnichenkoan@ilove-netology.com      
      PGADMIN_DEFAULT_PASSWORD: miroshnichenkoan12!3!!    
    ports:      
      - 61231:80    
    networks:      
      miroshnichenkoan-my-netology-hw:        
        ipv4_address: 172.22.0.3    
    restart: always
  zabbix-server:    
    image: zabbix/zabbix-server-pgsql    
    links:      
      - miroshnichenkoan-netology-db    
    container_name: miroshnichenkoan-zabbix-netology    
    environment:      
      DB_SERVER_HOST: 172.22.0.2      
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: miroshnichenkoan12!3!!    
    ports:      
      - 10051:10051    
    networks:      
      miroshnichenkoan-my-netology-hw:        
        ipv4_address: 172.22.0.4    
    restart: always
  zabbix_wgui:    
    image: zabbix/zabbix-web-apache-pgsql    
    links:      
      - miroshnichenkoan-netology-db         
      - zabbix-server    
    container_name: miroshnichenkoan-netology-zabbix-frontend    
    environment:      
      DB_SERVER_HOST: '172.22.0.2'      
      POSTGRES_USER: 'postgres'      
      POSTGRES_PASSWORD: miroshnichenkoan12!3!!      
      ZBX_SERVER_HOST: "zabbix_wgui"        
      PHP_TZ: "Europe/Moscow"    
    ports:      
      - 80:8080      
      - 443:8443    
    networks:      
      miroshnichenkoan-my-netology-hw:        
        ipv4_address: 172.22.0.5    
    restart: always
networks:  
  miroshnichenkoan-my-netology-hw:  
    driver: bridge    
    ipam:      
      config:      
      - subnet: 172.22.0.0/24
